## pandas
> panadas is a powerfull python liabrary for manuplation an analysis of data 

>its a open source liabrary

> fast(built on top of numpy) flexible  and productive liabrary

In [134]:
! pip install pandas

Requirement already satisfied: pandas in c:\users\klemp\anaconda3\lib\site-packages (2.2.3)
Requirement already satisfied: numpy>=1.26.0 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2.1.3)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\klemp\anaconda3\lib\site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in c:\users\klemp\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)

In [135]:
import pandas as pd

In [136]:
pd.__version__

'2.2.3'

### creating series-one dimensional array(ds)with lable

In [137]:
l1 = [1,2,3,4,5]

In [138]:
pd.Series(l1)

0    1
1    2
2    3
3    4
4    5
dtype: int64

In [139]:
s=pd.Series(l1,index = ["a","b","c","d","e"],name = "my Series")

In [140]:
s

a    1
b    2
c    3
d    4
e    5
Name: my Series, dtype: int64

In [141]:
type(s)

pandas.core.series.Series

In [142]:
s.values

array([1, 2, 3, 4, 5])

## index in series are immutable

In [143]:
s.index[0]='z'

TypeError: Index does not support mutable operations

In [ ]:
#changeing the index of pandas series

s.rename(index={'b':'y'},inplace=True)
s

a    1
y    2
c    3
d    4
e    5
Name: my Series, dtype: int64

### data frame - its a 2d array(just like a tables)

In [ ]:
dict1 = {'Name':['virat','Rohit','Dhoni','jadeja','Bumrah','Shami'] ,
         'Age':[34,33,40,32,30,40] ,
         'Marks':[85,90,75,80,70,80] ,
         'Role':['Batsman','Batsman','Wicket keeper','All Rounder','Bowler','bowler']
}
df=pd.DataFrame(dict1)

In [ ]:
type(df)

pandas.core.frame.DataFrame

In [ ]:
df.head

<bound method NDFrame.head of      Name  Age  Marks           Role
0   virat   34     85        Batsman
1   Rohit   33     90        Batsman
2   Dhoni   40     75  Wicket keeper
3  jadeja   32     80    All Rounder
4  Bumrah   30     70         Bowler
5   Shami   40     80         bowler>

In [ ]:
df.head(4)

     Name  Age  Marks           Role
0   virat   34     85        Batsman
1   Rohit   33     90        Batsman
2   Dhoni   40     75  Wicket keeper
3  jadeja   32     80    All Rounder

In [ ]:
df.tail

<bound method NDFrame.tail of      Name  Age  Marks           Role
0   virat   34     85        Batsman
1   Rohit   33     90        Batsman
2   Dhoni   40     75  Wicket keeper
3  jadeja   32     80    All Rounder
4  Bumrah   30     70         Bowler
5   Shami   40     80         bowler>

In [ ]:
df.tail(2)

     Name  Age  Marks    Role
4  Bumrah   30     70  Bowler
5   Shami   40     80  bowler

In [ ]:
len(df)

6

In [ ]:
df.count()

Name     6
Age      6
Marks    6
Role     6
dtype: int64

In [ ]:
type(df['Name'])

pandas.core.series.Series

In [ ]:
df['Name'].value_counts()

Name
virat     1
Rohit     1
Dhoni     1
jadeja    1
Bumrah    1
Shami     1
Name: count, dtype: int64

### Basic operation

> Importing data set from different files

> Importing tabular dataset

In [ ]:
stock_df = pd.read_csv(r'C:\Users\klemp\OneDrive\Desktop\Data analyst(DA)\Data sets\ETH_1h.csv')

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df.head() #top 5 rows

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71

In [ ]:
stock_df.head(10)

               Date  Symbol    Open    High     Low   Close      Volume
0  2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1  2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2  2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3  2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4  2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
5  2020-03-13 03-PM  ETHUSD  128.39  128.90  116.06  124.85  7378976.00
6  2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
7  2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
8  2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
9  2020-03-13 11-AM  ETHUSD  132.60  133.17  126.01  128.93  3311080.29

# Bottom 5 rows

In [ ]:
stock_df.tail()

                   Date  Symbol    Open    High    Low   Close      Volume
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.0  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.0  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.0  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.0  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.1  275.01   679358.87

In [ ]:
## number of rows in dataframe
len(stock_df)

> Access column names of dataframe

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

In [ ]:
###accsesing a column in dataframe
stock_df['Open']

0        129.94
1        119.51
2        124.47
3        124.08
4        124.85
          ...
23669    265.74
23670    268.79
23671    274.83
23672    275.01
23673    279.98
Name: Open, Length: 23674, dtype: float64

In [ ]:
### Accsesing multiple  a column in data
stock_df[['Open','Close','Volume']]

         Open   Close      Volume
0      129.94  128.71  1940673.93
1      119.51  129.94  7579741.09
2      124.47  119.51  4898735.81
3      124.08  124.47  2753450.92
4      124.85  124.08  4461424.71
...       ...     ...         ...
23669  265.74  272.57  1500282.55
23670  268.79  265.74  1702536.85
23671  274.83  268.79  3010787.99
23672  275.01  274.83   824362.87
23673  279.98  275.01   679358.87

[23674 rows x 3 columns]

# Acessing rows of dataframe

In [ ]:
stock_df.index

RangeIndex(start=0, stop=23674, step=1)

In [ ]:
stock_df.columns

Index(['Date', 'Symbol', 'Open', 'High', 'Low', 'Close', 'Volume'], dtype='object')

## Accessing rows

>  loc-label location

> df[row,col] #syntax

In [ ]:
stock_df.loc[23672]

Date      2017-07-01 12-PM
Symbol              ETHUSD
Open                275.01
High                275.01
Low                  271.0
Close               274.83
Volume           824362.87
Name: 23672, dtype: object

In [ ]:
stock_df.loc[23672,'Date']

'2017-07-01 12-PM'

In [ ]:
stock_df.loc[23672,['Date','Open','Close']]

Date     2017-07-01 12-PM
Open               275.01
Close              274.83
Name: 23672, dtype: object

### slicing in loc(lable location)

In [ ]:
stock_df.loc[23672,'Open':'Close'] #a:b both are inclusive

Open     275.01
High     275.01
Low       271.0
Close    274.83
Name: 23672, dtype: object

### iloc-index based locatin , when we don know labels for rows and column

In [ ]:
stock_df.iloc[1,2]#row index and column index

np.float64(119.51)

In [ ]:
stock_df.iloc[1,[2,4]]

Open    119.51
Low      117.1
Name: 1, dtype: object

In [ ]:
stock_df.iloc[1,2:6]

Open     119.51
High     132.02
Low       117.1
Close    129.94
Name: 1, dtype: object

In [ ]:
stock_df.iloc[1:6,2:6]

     Open    High     Low   Close
1  119.51  132.02  117.10  129.94
2  124.47  124.85  115.50  119.51
3  124.08  127.42  121.63  124.47
4  124.85  129.51  120.17  124.08
5  128.39  128.90  116.06  124.85

In [ ]:
f1=stock_df['High']>130

stock_gt_130 = stock_df[f1]

In [ ]:
stock_gt_130.reset_index(drop=True,inplace=True)
stock_gt_130

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 02-PM  ETHUSD  134.03  137.90  125.50  128.39  3733916.89
3      2020-03-13 01-PM  ETHUSD  131.35  140.95  128.99  134.03  9582732.93
4      2020-03-13 12-PM  ETHUSD  128.93  134.60  126.95  131.35  3906590.52
...                 ...     ...     ...     ...     ...     ...         ...
21608  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
21609  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
21610  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
21611  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
21612  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[21613 rows x 7 columns]

## Adding new column

In [ ]:
len(stock_df)

23674

In [ ]:
stock_df['Random_col']=list(range(1,len(stock_df)+1))

In [ ]:
stock_df

,Date,Symbol,Open,High,Low,Close,Volume,Random_col
0,2020-03-13 08-PM,ETHUSD,129.94,131.82,126.87,128.71,1940673.93,1
1,2020-03-13 07-PM,ETHUSD,119.51,132.02,117.10,129.94,7579741.09,2
2,2020-03-13 06-PM,ETHUSD,124.47,124.85,115.50,119.51,4898735.81,3
3,2020-03-13 05-PM,ETHUSD,124.08,127.42,121.63,124.47,2753450.92,4
4,2020-03-13 04-PM,ETHUSD,124.85,129.51,120.17,124.08,4461424.71,5
...,...,...,...,...,...,...,...,...
23669,2017-07-01 03-PM,ETHUSD,265.74,272.74,265.00,272.57,1500282.55,23670
23670,2017-07-01 02-PM,ETHUSD,268.79,269.90,265.00,265.74,1702536.85,23671
23671,2017-07-01 01-PM,ETHUSD,274.83,274.93,265.00,268.79,3010787.99,23672
23672,2017-07-01 12-PM,ETHUSD,275.01,275.01,271.00,274.83,824362.87,23673
23673,2017-07-01 11-AM,ETHUSD,279.98,279.99,272.10,275.01,679358.87,23674

### droping column

In [ ]:
stock_df.drop(columns=['Random_col'],inplace=True)

In [ ]:
stock_df

                   Date  Symbol    Open    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  129.94  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  119.51  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.47  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  124.08  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  124.85  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...     ...         ...
23669  2017-07-01 03-PM  ETHUSD  265.74  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  268.79  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.83  274.93  265.00  268.79  3010787.99
23672  2017-07-01 12-PM  ETHUSD  275.01  275.01  271.00  274.83   824362.87
23673  2017-07-01 11-AM  ETHUSD  279.98  279.99  272.10  275.01   679358.87

[23674 rows x 7 columns]

In [ ]:
stock_df.drop(['symbol'],axis=1,inplace=True)

KeyError: "['symbol'] not found in axis"

>droping row

In [ ]:
stock_df.drop(23672,axis=0,inplace=True)

In [ ]:
stock_df

                   Date  Symbol    High     Low   Close      Volume
0      2020-03-13 08-PM  ETHUSD  131.82  126.87  128.71  1940673.93
1      2020-03-13 07-PM  ETHUSD  132.02  117.10  129.94  7579741.09
2      2020-03-13 06-PM  ETHUSD  124.85  115.50  119.51  4898735.81
3      2020-03-13 05-PM  ETHUSD  127.42  121.63  124.47  2753450.92
4      2020-03-13 04-PM  ETHUSD  129.51  120.17  124.08  4461424.71
...                 ...     ...     ...     ...     ...         ...
23667  2017-07-01 05-PM  ETHUSD  268.44  262.39  263.51  1894983.33
23668  2017-07-01 04-PM  ETHUSD  272.57  267.60  268.00  1287300.75
23669  2017-07-01 03-PM  ETHUSD  272.74  265.00  272.57  1500282.55
23670  2017-07-01 02-PM  ETHUSD  269.90  265.00  265.74  1702536.85
23671  2017-07-01 01-PM  ETHUSD  274.93  265.00  268.79  3010787.99

[23672 rows x 6 columns]